trigger:
- master  # Define the branch to trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'  # Use an appropriate agent pool

variables:
  azureServiceConnection: 'sakshi'  # Replace with your Azure service connection name
  containerRegistry: 'sakshi1233.azurecr.io'  # Replace with your Azure Container Registry URL
  containerAppName: 'mlk'  # Replace with your desired Azure Container App name
  resourceGroup: 'Sakshi-rg'  # Replace with your Azure Resource Group name

stages:
- stage: BuildAndPush
  jobs:
  - job: BuildAndPush
    displayName: 'Build and Push Docker Image'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'  # Use Python 3.x
        addToPath: true     # Add Python to PATH-
    - task: Docker@2
      inputs:
       containerRegistry: 'kkl'
       repository: 'project12'
       command: 'buildAndPush'
       Dockerfile: '**/Dockerfile'
       tags: 'latest'
-
 stage: DeployToAzureContainerApps
 jobs:
  - job: DeployContainerApp
    displayName: 'Deploy to Azure Container Apps'
    steps:
    - task: AzureContainerApps@1
      inputs:
        azureSubscription: $(azureServiceConnection)
        containerAppName: $(containerAppName)
        appSourcePath: 'project12:latest'
        resourceGroup: $(resourceGroup)
        acrName: $(containerRegistry)
